  AWSOrganizationalUnit:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.ap-southeast-1.amazonaws.com/aws-test/template.yaml
      Parameters:
        RootId: !Ref RootId