AWSTemplateFormatVersion: '2010-09-09'
Description: Parent stack to create S3 bucket and deploy nested stacks.

Parameters:
  S3BucketName:
    Description: S3 bucket name for the Nested Stacks. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String
    Default: NestedStacksBucket

Resources:
  AWSTestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.ap-southeast-1.amazonaws.com/aws-test/template.yaml