AWSTemplateFormatVersion: '2010-09-09'
Description: Enable GuardDuty in Administrator Account

Resources:
  GuardDutyDetector:
    Type: 'AWS::GuardDuty::Detector'
    Properties:
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES
      DataSources:
        S3Logs:
          Enable: true